# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carType', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastLat', models.FloatField(default=0)),
                ('lastLong', models.FloatField(default=0)),
                ('parked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
